"""Training-free vocabulary transport utilities."""

from .artifact import (
    ArtifactError,
    TransportArtifact,
    artifact_from_dense,
    load_transport_artifact,
    save_transport_artifact,
)
from .approximations import (
    ApproximationError,
    ApproximationErrorReport,
    approximation_error,
    chunked_transport_embeddings,
    hard_transport_embeddings,
    precompute_source_values,
    precomputed_transport_embeddings,
)
from .ann_candidates import (
    AnnCandidateError,
    ByteLshConfig,
    build_bidirectional_lsh_candidates,
)
from .baseline import (
    BaselineError,
    BaselineSnapshot,
    collect_runtime_info,
    freeze_baseline,
    save_baseline,
)
from .audit import (
    audit_markdown,
    audit_transport_artifact,
    save_audit,
    transport_to_dense,
)
from .candidate_graph import (
    CandidateEdge,
    CandidateGraph,
    CandidateGraphError,
    EdgeSource,
    accumulate_byte_span_counts,
    augment_candidate_graph_for_marginals,
    build_candidate_graph,
)
from .config import (
    ConfigError,
    DataSpec,
    ModelSpec,
    TransportConfig,
    TransportConstructionSpec,
    TransportInferenceSpec,
)
from .corpus import (
    CorpusError,
    build_corpus_manifest,
    canonical_messages,
    canonical_sample_id,
    file_sha256,
    load_manifest_texts,
)
from .corpus_materialization import MaterializationError, materialize_corpus
from .manifest import (
    ManifestError,
    build_transport_manifest,
    save_manifest,
    serialize_manifest,
)
from .marginals import MarginalError, TokenMarginal, estimate_token_marginal
from .metrics import MetricsError, TransportMetrics
from .orf import (
    OrfError,
    OrfTransportState,
    apply_orf_transport,
    build_orf_directions,
    build_orf_transport_state,
    positive_orf_features,
)
from .sinkhorn import (
    ConvergenceReport,
    SparseCoupling,
    SinkhornError,
    candidate_edge_costs,
    conditional_from_coupling,
    dense_sinkhorn,
    sparse_conditional_from_coupling,
    sparse_log_sinkhorn,
)
from .token_metadata import (
    TokenMetadata,
    encode_with_byte_spans,
    exact_byte_matches,
    iter_token_metadata,
    ordinary_bytes_index,
    special_id_to_kind,
    special_id_to_token,
    token_raw_bytes,
    tokenizer_fingerprint,
)
from .soft_transport import (
    SoftTransportError,
    SoftTransportStats,
    transport_embeddings,
    transport_probabilities,
    source_probabilities,
)
from .vocab_transport import (
    LocalTransportArtifact,
    VocabTransportBuildResult,
    build_small_transport,
    build_vocab_transport,
    load_transport,
    save_transport,
)
from .wrapper import (
    TrainingFreeTransportModel,
    TransportGenerationOutput,
    TransportModelError,
    TransportPrefill,
    VirtualPrompt,
)

__all__ = [
    "AnnCandidateError",
    "ApproximationError",
    "ApproximationErrorReport",
    "ArtifactError",
    "BaselineError",
    "BaselineSnapshot",
    "ByteLshConfig",
    "CandidateEdge",
    "CandidateGraph",
    "CandidateGraphError",
    "ConvergenceReport",
    "ConfigError",
    "CorpusError",
    "DataSpec",
    "EdgeSource",
    "LocalTransportArtifact",
    "ManifestError",
    "MaterializationError",
    "MarginalError",
    "MetricsError",
    "ModelSpec",
    "OrfError",
    "OrfTransportState",
    "SinkhornError",
    "SparseCoupling",
    "SoftTransportError",
    "SoftTransportStats",
    "TransportArtifact",
    "TransportConfig",
    "TransportConstructionSpec",
    "TransportInferenceSpec",
    "TransportMetrics",
    "TrainingFreeTransportModel",
    "TransportGenerationOutput",
    "TransportModelError",
    "TransportPrefill",
    "VirtualPrompt",
    "VocabTransportBuildResult",
    "TokenMetadata",
    "TokenMarginal",
    "accumulate_byte_span_counts",
    "artifact_from_dense",
    "approximation_error",
    "apply_orf_transport",
    "audit_markdown",
    "audit_transport_artifact",
    "augment_candidate_graph_for_marginals",
    "build_small_transport",
    "build_vocab_transport",
    "build_transport_manifest",
    "candidate_edge_costs",
    "build_candidate_graph",
    "build_bidirectional_lsh_candidates",
    "build_corpus_manifest",
    "build_orf_directions",
    "build_orf_transport_state",
    "canonical_messages",
    "canonical_sample_id",
    "conditional_from_coupling",
    "collect_runtime_info",
    "dense_sinkhorn",
    "encode_with_byte_spans",
    "exact_byte_matches",
    "estimate_token_marginal",
    "freeze_baseline",
    "file_sha256",
    "iter_token_metadata",
    "load_transport",
    "load_manifest_texts",
    "materialize_corpus",
    "load_transport_artifact",
    "ordinary_bytes_index",
    "positive_orf_features",
    "precompute_source_values",
    "precomputed_transport_embeddings",
    "save_transport",
    "save_transport_artifact",
    "save_manifest",
    "save_baseline",
    "save_audit",
    "serialize_manifest",
    "special_id_to_kind",
    "special_id_to_token",
    "token_raw_bytes",
    "tokenizer_fingerprint",
    "transport_to_dense",
    "transport_embeddings",
    "transport_probabilities",
    "source_probabilities",
    "hard_transport_embeddings",
    "chunked_transport_embeddings",
    "sparse_conditional_from_coupling",
    "sparse_log_sinkhorn",
]
